### PR TITLE
remove Win64 from second paramter in polly_init

### PR DESCRIPTION
**Pull request by Dargun**
vs15 needs as second paramter "Visual Studio 15 2017 Win64"
vs16  needs as second paramter "Visual Studio 16 2019"
with "Visual Studio 16 2019 Win64" i got that error 
< Please change generator to: Visual Studio 16 2019 Win64
(Current generator: Visual Studio 16 2019)

why is that different on each visual studio version?

### CODE REVIEW

**Comment by NeroBurner** [comment]
because CMake (and maybe Visual Studio itself, but I'm not sure) changed the generator string behavior for VS 16 2019 and onwards. With newer generators one must use the generator architecture `-A` argument (and maybe the generator toolset `-T`) instead of the `Win64` inside the generator string

**Comment by NeroBurner** [comment]
The error message sounds the wrong way around. CMake normally tells you to use `-G "Visual Studio 16 2019 -A x64"` instead of `-G "Visual Studio 16 2019 Win64"`. Maybe the pollly error message is wrong?

ninja-edit: add `-A x64` in recommended commandline option

**Comment by Dargun** [comment]
> The error message sounds the wrong way around. CMake normally tells you to use `-G "Visual Studio 16 2019 -A x64"` instead of `-G "Visual Studio 16 2019 Win64"`. Maybe the pollly error message is wrong?
> 
> ninja-edit: add `-A x64` in recommended commandline option

Yea thats why instead Win64 it needs for vs16 the include of "vs-platform-x64.cmake"
This was not clear in my understanding. but now it makes all sense :)

**Comment by NeroBurner** [comment]
@rbsheth please merge

**Pull request merged**
